"""baseline_schema

Revision ID: 434bebe9f1fb
Revises: 
Create Date: 2025-10-31 11:48:43.475207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '434bebe9f1fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create compression_algorithms table
    op.create_table('compression_algorithms',
        sa.Column('id', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('category', sa.String(length=50), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('version', sa.String(length=20), nullable=True),
        sa.Column('is_enabled', sa.Boolean(), nullable=True),
        sa.Column('supported_levels', sa.JSON(), nullable=True),
        sa.Column('best_for', sa.JSON(), nullable=True),
        sa.Column('speed_rating', sa.String(length=20), nullable=True),
        sa.Column('compression_efficiency', sa.String(length=20), nullable=True),
        sa.Column('memory_usage', sa.String(length=20), nullable=True),
        sa.Column('cpu_intensity', sa.String(length=20), nullable=True),
        sa.Column('avg_compression_ratio', sa.DECIMAL(precision=5, scale=3), nullable=True),
        sa.Column('avg_compression_speed_mbps', sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column('avg_decompression_speed_mbps', sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column('success_rate_percent', sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column('parameters_schema', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # Create compression_requests table
    op.create_table('compression_requests',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('request_id', sa.String(length=100), nullable=False),
        sa.Column('algorithm_id', sa.String(length=50), nullable=False),
        sa.Column('compression_level', sa.Integer(), nullable=True),
        sa.Column('input_content_hash', sa.String(length=64), nullable=False),
        sa.Column('input_size_bytes', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('priority', sa.Integer(), nullable=True),
        sa.Column('output_content_hash', sa.String(length=64), nullable=True),
        sa.Column('output_size_bytes', sa.Integer(), nullable=True),
        sa.Column('compression_ratio', sa.DECIMAL(precision=8, scale=4), nullable=True),
        sa.Column('compression_time_ms', sa.Integer(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=True),
        sa.Column('max_retries', sa.Integer(), nullable=True),
        sa.Column('submitted_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('started_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('parameters', sa.JSON(), nullable=True),
        sa.Column('user_id', sa.String(length=100), nullable=True),
        sa.Column('request_source', sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(['algorithm_id'], ['compression_algorithms.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_compression_requests_status'), 'compression_requests', ['status'], unique=False)
    op.create_index(op.f('ix_compression_requests_algorithm'), 'compression_requests', ['algorithm_id'], unique=False)
    op.create_index(op.f('ix_compression_requests_submitted'), 'compression_requests', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_compression_requests_priority'), 'compression_requests', ['priority'], unique=False)

    # Create system_monitoring_metrics table
    op.create_table('system_monitoring_metrics',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('recorded_at', sa.TIMESTAMP(), nullable=False),
        sa.Column('metric_type', sa.String(length=50), nullable=False),
        sa.Column('cpu_percent', sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column('memory_percent', sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column('disk_percent', sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column('network_bytes_per_sec', sa.BIGINT(), nullable=True),
        sa.Column('compression_efficiency', sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column('throughput_bytes_per_sec', sa.BIGINT(), nullable=True),
        sa.Column('success_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column('error_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column('avg_compression_ratio', sa.DECIMAL(precision=10, scale=4), nullable=True),
        sa.Column('avg_response_time_ms', sa.Integer(), nullable=True),
        sa.Column('p50_response_time_ms', sa.Integer(), nullable=True),
        sa.Column('p95_response_time_ms', sa.Integer(), nullable=True),
        sa.Column('p99_response_time_ms', sa.Integer(), nullable=True),
        sa.Column('system_health', sa.String(length=20), nullable=False),
        sa.Column('active_connections', sa.Integer(), nullable=True),
        sa.Column('queue_length', sa.Integer(), nullable=True),
        sa.Column('algorithm_performance', sa.JSON(), nullable=True),
        sa.Column('host_name', sa.String(length=255), nullable=True),
        sa.Column('instance_id', sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_monitoring_metrics_recorded_at'), 'system_monitoring_metrics', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
